import { type Node, type Edge, MarkerType } from "reactflow";

export interface Template {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  nodes: Node[];
  edges: Edge[];
}

export const templates: Template[] = [
  {
    id: "email-automation",
    title: "Email Automation",
    description: "Automate email responses based on incoming messages",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "New Email Received" },
      },
      {
        id: "2",
        type: "condition",
        position: { x: 250, y: 250 },
        data: { label: "Contains Keywords?" },
      },
      {
        id: "3",
        type: "action",
        position: { x: 100, y: 400 },
        data: { label: "Tag as Important" },
      },
      {
        id: "4",
        type: "email",
        position: { x: 400, y: 400 },
        data: { label: "Send Auto-Reply" },
      },
      {
        id: "5",
        type: "notification",
        position: { x: 100, y: 550 },
        data: { label: "Notify Team" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        label: "Yes",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-4",
        source: "2",
        target: "4",
        label: "No",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
  {
    id: "data-processing",
    title: "Data Processing Pipeline",
    description: "Process and transform data from multiple sources",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "New Data Available" },
      },
      {
        id: "2",
        type: "action",
        position: { x: 250, y: 250 },
        data: { label: "Extract Data" },
      },
      {
        id: "3",
        type: "action",
        position: { x: 250, y: 400 },
        data: { label: "Transform Data" },
      },
      {
        id: "4",
        type: "condition",
        position: { x: 250, y: 550 },
        data: { label: "Validation Check" },
      },
      {
        id: "5",
        type: "database",
        position: { x: 100, y: 700 },
        data: { label: "Store in Database" },
      },
      {
        id: "6",
        type: "notification",
        position: { x: 400, y: 700 },
        data: { label: "Report Error" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        label: "Valid",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-6",
        source: "4",
        target: "6",
        label: "Invalid",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
  {
    id: "social-media",
    title: "Social Media Integration",
    description: "Automate posting across multiple social platforms",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "Content Created" },
      },
      {
        id: "2",
        type: "action",
        position: { x: 250, y: 250 },
        data: { label: "Format Content" },
      },
      {
        id: "3",
        type: "condition",
        position: { x: 250, y: 400 },
        data: { label: "Has Images?" },
      },
      {
        id: "4",
        type: "action",
        position: { x: 100, y: 550 },
        data: { label: "Optimize Images" },
      },
      {
        id: "5",
        type: "action",
        position: { x: 250, y: 700 },
        data: { label: "Schedule Post" },
      },
      {
        id: "6",
        type: "notification",
        position: { x: 400, y: 550 },
        data: { label: "Text-Only Format" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        label: "Yes",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-6",
        source: "3",
        target: "6",
        label: "No",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e6-5",
        source: "6",
        target: "5",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
  {
    id: "customer-onboarding",
    title: "Customer Onboarding",
    description: "Streamline the customer onboarding process",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "New Sign Up" },
      },
      {
        id: "2",
        type: "email",
        position: { x: 250, y: 250 },
        data: { label: "Welcome Email" },
      },
      {
        id: "3",
        type: "delay",
        position: { x: 250, y: 400 },
        data: { label: "Wait 2 Days" },
      },
      {
        id: "4",
        type: "condition",
        position: { x: 250, y: 550 },
        data: { label: "Completed Profile?" },
      },
      {
        id: "5",
        type: "email",
        position: { x: 100, y: 700 },
        data: { label: "Profile Reminder" },
      },
      {
        id: "6",
        type: "action",
        position: { x: 400, y: 700 },
        data: { label: "Add to Segment" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        label: "No",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-6",
        source: "4",
        target: "6",
        label: "Yes",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
  {
    id: "approval-process",
    title: "Approval Process",
    description: "Manage document approvals with notifications",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "Document Submitted" },
      },
      {
        id: "2",
        type: "notification",
        position: { x: 250, y: 250 },
        data: { label: "Notify Approver" },
      },
      {
        id: "3",
        type: "condition",
        position: { x: 250, y: 400 },
        data: { label: "Approved?" },
      },
      {
        id: "4",
        type: "action",
        position: { x: 100, y: 550 },
        data: { label: "Request Changes" },
      },
      {
        id: "5",
        type: "email",
        position: { x: 400, y: 550 },
        data: { label: "Confirmation Email" },
      },
      {
        id: "6",
        type: "database",
        position: { x: 400, y: 700 },
        data: { label: "Update Records" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        label: "No",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-5",
        source: "3",
        target: "5",
        label: "Yes",
        labelBgPadding: [8, 4],
        labelBgBorderRadius: 4,
        labelBgStyle: { fill: "#f8fafc", fillOpacity: 0.7 },
        labelStyle: { fill: "#475569", fontSize: 12 },
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e5-6",
        source: "5",
        target: "6",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
  {
    id: "event-registration",
    title: "Event Registration",
    description: "Manage event registrations and reminders",
    thumbnail: "/placeholder.svg?height=200&width=400",
    nodes: [
      {
        id: "1",
        type: "trigger",
        position: { x: 250, y: 100 },
        data: { label: "Registration Received" },
      },
      {
        id: "2",
        type: "email",
        position: { x: 250, y: 250 },
        data: { label: "Confirmation Email" },
      },
      {
        id: "3",
        type: "database",
        position: { x: 250, y: 400 },
        data: { label: "Add to Attendees" },
      },
      {
        id: "4",
        type: "schedule",
        position: { x: 250, y: 550 },
        data: { label: "Schedule Reminder" },
      },
      {
        id: "5",
        type: "delay",
        position: { x: 100, y: 700 },
        data: { label: "1 Day Before" },
      },
      {
        id: "6",
        type: "email",
        position: { x: 400, y: 700 },
        data: { label: "Event Details" },
      },
    ],
    edges: [
      {
        id: "e1-2",
        source: "1",
        target: "2",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e2-3",
        source: "2",
        target: "3",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e3-4",
        source: "3",
        target: "4",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-5",
        source: "4",
        target: "5",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
      {
        id: "e4-6",
        source: "4",
        target: "6",
        style: { stroke: "#94a3b8", strokeWidth: 1.5 },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: "#94a3b8",
          width: 15,
          height: 15,
        },
      },
    ],
  },
];
